### ISSUE TITLE
Be able to find out what port a service is running by searching for the port

### ISSUE THREAD

**Issue by TomDudley92** [hmrc/sm-hub-frontend#1]
Can this feature be added as it would be useful to be able to search for a port and have the relevant service shown

**Comment by Smudgey** [comment]
@chrisjwwalker @TomDudley92 Is this partial match by port or exact match only?

Partial Search Eg: Search with 943 shows all services who have '943' in their port
Exact Match Eq: Search with 943 shows nothing, would need an exact port such as 9435 (AGENT_FI_ACCESS_CONTROL)

**Comment by chrisjwwalker** [comment]
@Smudgey I would say exact match, might be best potentially, depends if @TomDudley92 had another idea

**Comment by TomDudley92** [comment]
When I came across this issue I was trying to do an exact match. Both ideas are would help to solve the issue

**Comment by Smudgey** [comment]
Okay, i'll do a version that allows partial & exact matching, at the end of the day it provides an extra option
