### ISSUE TITLE
Display service logs

### ISSUE THREAD

**Issue by chrisjwwalker** [hmrc/sm-hub-frontend#14]
From running services, have a view logs on the tile that opens something with the logs

**Comment by jmountain-hmrc** [comment]
Here's an initial cut of what I've made for this issue.

* Adds a log button to each service on the services list display
* Displays the sm -l of each service in a tidy format, monospace font friendly format. I've still yet to do styling for dark mode.

![screenshot from 2018-06-29 16-07-09](https://user-images.githubusercontent.com/31282623/42100080-217f8e0e-7bb7-11e8-84f7-bf5f6e6ef61f.png)
![screenshot from 2018-06-29 16-10-55](https://user-images.githubusercontent.com/31282623/42100093-2b0504ae-7bb7-11e8-9a44-f196ef8d3bfc.png)
